### ISSUE TITLE
Out of memory: terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by xanxanxan** [sritterbusch/ospac#2]
Whenever I run ospac on my (fairly old, ~10 years) computer, I get an output like this:

xan@xan:~/Desktop/Aufnahme/ZOOM0002$ ospac ZOOM0002_Tr1.WAV ZOOM0002_Tr2.WAV --output test.wav
ospac 1.0 built Mar 17 2016 11:00:27
   0.00 Wave.cpp:23                 Loading ZOOM0002_Tr1.WAV
   0.00 Wave.cpp:40                 Reading 97445824 frames with 1 channels with rate 48000
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Abgebrochen (Speicherabzug geschrieben)

It also happens when I run ospac with different flags ('ospac ZOOM0002_Tr1.WAV ZOOM0002_Tr2.WAV ZOOM0002_Tr4.WAV --leveler --no-normalize --multi' for example).
Additional information seems to be written to some log file, but I don’t know where it is.

The WAV files come from my Zoom H6.

**Comment by sritterbusch** [comment]
The error message is misleading- this just means that the process went out of memory, already when loading the first file.

Internally, ospac renders in at least 32bit per sample (64bit when needed) and keeps several copies of input in memory, at times. Since your project is 0.5GB at 16bit, you need well above 1GB to process your files in ospac at the moment.

To solve your problem either add RAM to the system or increase your swap space. On linux, you can do this as root to add 4GB of swap temporarily ([reference for this](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/3/html/System_Administration_Guide/s1-swap-adding.html)):

```
# dd if=/dev/zero of=/swapfile bs=1048576 count=4096
# mkswap /swapfile
# swapon /swapfile
```

Then, you should be able to use ospac for your files. To activate this swap space extension in your system permanently, you need to add this line to your `/etc/fstab`:
`/swapfile               swap                    swap    defaults        0 0`

Support for virtual audio segments, that do not have to be in-memory all the time, is on the to-do list- but it isn't the main priority considering the size of RAM in current systems.

**Comment by xanxanxan** [comment]
Thanks for the great support of your software! The temporary swap increase totally solved the issue, although executing is very long as you can imagine. But that’s an issue with my computer.
